[package]
name = "rustini-derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustini_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro-error = "*"
proc-macro2 = "*"
quote = "*"
rustini-core = { path = "../rustini-core" }
syn = { version = "*", features = ["full"] }
